#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "引数が空です"
  exit 1
fi

if [ "$1" == "-all" ]; then
    echo "all is called"
    exit 0
elif [[ "$1" =~ -.* ]]; then
    echo "不明な引数「$1」が使用されました"
    exit 1
else
    if [ "$#" -eq 1 ]; then
        python3 /home/a1024/cpp/Competitive-Programming-Library/checker/_run_test/judge_genre.py $1 d
        exit 0
    fi
    if [ "$2" != "nd" ] && [ "$2" != "d" ]; then
        echo "不明な引数「$2」が使用されました"
        exit 1
    fi
    python3 /home/a1024/cpp/Competitive-Programming-Library/checker/_run_test/judge_genre.py $1 $2
    exit 0
fi
